### PR TITLE
better error handling 

### PR DESCRIPTION
**Pull request by angreebunny**

### CODE REVIEW

**Comment by angreebunny** [comment]
better error handling

**Comment by chrisdoman** [comment]
Tested and adding.

Many thanks @angreebunny  ! If you're happy to send your postal address to otx-support@alienvault.com I'll see if we can send you a t-shirt or something as a (small!) thankyou.

**Comment by angreebunny** [comment]
thank you for the consideration... 
I have been a fan of AlienVault's open source effort and this was the first time I have able to contribute back... The fact that you accepted my pull request helps my reputation as a programmer and that is all the thank i need.. so thank you ;) 

i hope i can find more way to help in the future...

**Comment by chrisdoman** [comment]
Hehe that's great- thanks :)

**Pull request closed without merging**
